<a href="https://colab.research.google.com/github/aniket2829/market-basket-analysis/blob/main/Market_basket_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
!pip install apyori

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: apyori in /usr/local/lib/python3.10/dist-packages (1.1.2)

In [21]:
# Importing basic libraries
import numpy as np #arrays
import pandas as pd #tabular
from apyori import apriori #association between two data items

In [22]:
# Loading Dataset
df = pd.read_csv("/content/store_data.csv", header=None)

In [23]:
# the first 10 rows of dataset
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,whole wheat pasta,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,soup,light cream,shallot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,frozen vegetables,spaghetti,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Shape of the dataset
df.shape

(7501, 20)

In [25]:
# create list of transactions (list)
records = []
for i in range(0, 7501):
    records.append([str(df.values[i,j]) for j in range(0, 20)])

In [26]:
rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
results = list(rules)

In [27]:
for item in results:
    pair = item[0]
    items = [i for i in pair]
    if items[0] == 'nan' or items[1] == 'nan':
        continue
    print("You should keep", items[1], "next to", items[0])

You should keep light cream next to chicken
You should keep mushroom cream sauce next to escalope
You should keep pasta next to escalope
You should keep herb & pepper next to ground beef
You should keep ground beef next to tomato sauce
You should keep whole wheat pasta next to olive oil
You should keep shrimp next to pasta
You should keep shrimp next to frozen vegetables
You should keep ground beef next to spaghetti
You should keep pasta next to escalope
You should keep spaghetti next to frozen vegetables
You should keep milk next to frozen vegetables
You should keep mineral water next to frozen vegetables
You should keep spaghetti next to frozen vegetables
You should keep spaghetti next to frozen vegetables
You should keep spaghetti next to frozen vegetables
You should keep spaghetti next to grated cheese
You should keep ground beef next to mineral water
You should keep herb & pepper next to ground beef
You should keep ground beef next to spaghetti
You should keep milk next to olive oil
You should keep ground beef next to tomato sauce
You should keep shrimp next to spaghetti
You should keep milk next to olive oil
You should keep mineral water next to olive oil
You should keep whole wheat pasta next to olive oil
You should keep shrimp next to pasta
You should keep spaghetti next to olive oil
You should keep shrimp next to frozen vegetables
You should keep ground beef next to spaghetti
You should keep spaghetti next to frozen vegetables
You should keep milk next to frozen vegetables
You should keep milk next to frozen vegetables
You should keep mineral water next to frozen vegetables
You should keep spaghetti next to frozen vegetables
You should keep spaghetti next to frozen vegetables
You should keep spaghetti next to frozen vegetables
You should keep spaghetti next to grated cheese
You should keep ground beef next to mineral water
You should keep ground beef next to spaghetti
You should keep milk next to olive oil
You should keep shrimp next to spaghetti
You should keep milk next to olive oil
You should keep mineral water next to olive oil
You should keep spaghetti next to olive oil
You should keep spaghetti next to milk